excluded:
    - Pods
    
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace # explicitly disabled
  - force_cast
  - xctfail_message
  - variable_name
  - multiple_closures_with_trailing_closure
  - for_where
  
function_body_length:
    warning: 150
    error: 300

file_length:
    warning: 500
    error: 1000
    
line_length:
    warning: 160
    error: 200
    
type_body_length:
    warning: 500
    error: 1000

force_try:
    severity: warning

